buildscript {
    repositories { maven { url = 'https://maven.minecraftforge.net/' }; mavenCentral(); gradlePluginPortal() }
    dependencies { classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT' }
}
apply plugin: 'net.minecraftforge.gradle.forge'
version = '1.0.0-r24'
group = 'cn.blockforge.generated.banishmentdimension'
archivesBaseName = 'banishment_dimension'
sourceCompatibility = targetCompatibility = '1.8'
minecraft { version = '1.12.2-14.23.5.2847'; runDir = 'run'; mappings = 'stable_39' }
tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }
processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.version
    from(sourceSets.main.resources.srcDirs) { include 'mcmod.info'; expand 'version': project.version, 'mcversion': project.minecraft.version }
    from(sourceSets.main.resources.srcDirs) { exclude 'mcmod.info' }
}
